### ISSUE TITLE
"Unofficial client" is ambiguous with "Official release"

### ISSUE THREAD

**Issue by slook** [jackBonadies/SeekerAndroid#10]
"Official release" is mentioned on the project description, so consider changing the main project 'About' string from "Unofficial Soulseek Client for Android" to...
+ "Android client for the Soulseek peer-to-peer network"

Since the official Soulseek client does not have an Android version, there is no need to state that the app is unofficial, especially considering that Seeker is the only working client for the target platform at the present time. The community consider it to be...
+ "**_The_** Soulseek client for Android"

**Comment by jackBonadies** [comment]
Good suggestion! Updated Github About section.
