### ISSUE TITLE
Missing Wishlist and Privileges features

### ISSUE THREAD

**Issue by slook** [jackBonadies/SeekerAndroid#11]
According to the Soulseek Rules at https://www.slsknet.org/news/node/681 :

> "Alternative clients for platforms other than Microsoft(r) Windows(r) that implement the full range of features of the Soulseek® Network ... are tolerated" ...
> _"(including chat, search, wishlist, download, upload, and respect / recognition of privileges)"_

However Wishlist and Privileges are lacking features according to [README.md](README.md) :

> _"supporting downloading, searching, sharing, messages, chatrooms, port forwarding, and more."_

Unless the missing features are already included in "_and more_", then I suppose it is technically necessary to add the missing features into the application for it to be a "tolerated" client on the network.

If the features are already present in the application, then the text in README.md should be changed to reflect this.

**Comment by jackBonadies** [comment]
Yes both Wishlist and Privileges features are included in the application.  I will update the readme.

**Comment by jackBonadies** [comment]
Updated README.md with commit 17613bee34a1794efcfccf682147999c26c1f7d7

**Comment by slook** [comment]
Nice work :)
