### ISSUE TITLE
Bug: toast "Requesting private room creation" regardless of "Make Private" checkbox setting

### ISSUE THREAD

**Issue by Efreak** [jackBonadies/SeekerAndroid#13]
When you create a room, regardless of whether you check the *Make Private* box, a today pops up afterwards that says *Requesting private room creation*. This is confusing.

**Comment by jackBonadies** [comment]
Thanks for pointing that out.  Fixing this now.

**Comment by jackBonadies** [comment]
Fixed with commit - 59bf0215bd9746b5c5f7060389c7f7a7fbedabd5
