### ISSUE TITLE
Soulseek blocks some searches

### ISSUE THREAD

**Issue by kgbandido** [jackBonadies/SeekerAndroid#14]
This is a known issue with soulseek itself and if it isnt serverside is there a way to buypass this within the code?

**Comment by jackBonadies** [comment]
This is implemented serverside.  For a search to take place (1) your client sends the search term to the server (2) the server sends the search term to everyone on the network (this is normally through the distributed network, not directly) and (3) if another client has matching results they connect to you directly to give them to you.  

Regardless of the search term, my client always does (1) and (3), it does not look at or filter out any terms before sending them to the server, or finding and sending matching search results to another client.  And so (2) is where the chain is broken (the server does not forward blocked terms).  

So its a good question, but unfortunately nothing that I can do about it.  As a workaround, assuming the blocked term is say an artist, omit the artist, and search either an album name, or a track name.  A bit annoying, but always works for me, at least.
