### ISSUE TITLE
Search is impossible in RTL layout

### ISSUE THREAD

**Issue by maemunman** [jackBonadies/SeekerAndroid#18]
If device is in right-to-left language, there is no text box in the search tab, so search terms cannot be typed by user.

![Screenshot_۲۰۲۲۰۲۱۵-۲۱۲۲۴۹_Seeker](https://user-images.githubusercontent.com/32847759/154195872-be5e1521-c2bb-44ea-a202-cb70661ff95c.jpg)

**Comment by jackBonadies** [comment]
Thanks for this. Apologies, as I had never tested Right to Left.  I will fix this ASAP.

**Comment by jackBonadies** [comment]
I made a fix for this.  I will upload a new version on github and playstore soon.

Currently Seeker has no translations for any Right to Left languages.  Is the preferred behavior in this case (1) Layout is Right To Left even though the language is Left To Right or (2) Layout should be Left to Right to match the default LTR (English in this case) language?  I looked it up and it said (2) but just making sure.

**Comment by maemunman** [comment]
Bless you brother, thank you for working on it so quickly.

I don't know what is correct— in practice it's just a terrible mess.  Different apps deal with RTL radically differently.  Some flip the layout, but don't flip the gesture, so swipe-right moves you leftwards.  Others swap both. Others swap neither.  Some apps swap the direction only of certain layout elements, but not others, ie: a  message app swapping the left-right alignment of user avatar but without swapping the alignment of the text bubbles. Big mess. So as long as it works, I cannot complain

**Comment by jackBonadies** [comment]
Thanks for the response!  I followed advice I found online stating that if the language displayed is left to right then the layout should be left to right.  However, if you try it out and that does not seem right I will be happy to change it, feel free to reopen the issue.  Even if right to left is forced via developer option "Force Right to Left" the bug where the search entry does not display is fixed :)  The release is version 2.8.6, see link below.  Available IzzyDroid and Google Play Store likely today or tomorrow. 

https://github.com/jackBonadies/SeekerAndroid/releases/tag/v2.8.6
