### ISSUE TITLE
Cannot select folders in my SD card as Shared Folders or Download Folders

### ISSUE THREAD

**Issue by FosRexx** [jackBonadies/SeekerAndroid#26]
App version: v2.9.12 from IzzyOnDroid Repo
Android: v12 LineageOS 19

I keep my music in my SD card and so I want to download songs directly to my SD card and also share my collection from my SD card but when I go to select a Download Folder or select a Shared Folders the list of folders in my Internal Storage show up, I go up a directory to "/storage/emulated", in there, there is only one option that is ".." and so I cannot even go back to my Internal Storage ("/storage/emulated/0") without canceling and again selecting the option to choose a Download Folder, and again if I go back a directory from "/storage/emulated" their is no options to go into my SD card and select a folder from SD card.

Default file manager disabled, Seeker uses its internal file browser to select folders.

**Comment by jackBonadies** [comment]
Thank you for the write up.  I was able to reproduce this on my end.  I am using the normal java file.ListFile() to list children.  In the case of /storage/emulated and /storage/ this method returns null (hence the observed behavior).  Expect a fix shortly.

**Comment by jackBonadies** [comment]
Should be fixed in latest release (will be up on IzzyDroid within 2 days typically).
https://github.com/jackBonadies/SeekerAndroid/releases/tag/v2.9.13

If still and issue or any other issues related to internal directory picker please lmk and reopen.
