### ISSUE TITLE
feature request: make app permanently run in background

### ISSUE THREAD

**Issue by ChuuqoVN** [jackBonadies/SeekerAndroid#31]
I want to keep my shared files up 24/7 for everyone to download but it seems like the app just got killed if I just close it in the recent apps view.

**Comment by jackBonadies** [comment]
I see, yeah for whatever reason I had a flag on the foreground service to end it when the task is removed from the task list.  I unset this flag and now it will stay alive as long as the service is running (ca6318eb9354f06e68e8928190e4c1dcb02c1ac0)

**Comment by ChuuqoVN** [comment]
So when will the app get updated on izzyondroid repo?

**Comment by jackBonadies** [comment]
Please give me about a week.  Looking to do some more testing and a bug fix before the release.

**Comment by jackBonadies** [comment]
@ChuuqoVN This should be all set v2.9.15, please let me know if there are any issues

**Comment by ChuuqoVN** [comment]
It works perfectly
