### ISSUE TITLE
Add summary catalog size

### ISSUE THREAD

**Issue by 154pinkchairs** [jackBonadies/SeekerAndroid#5]
as above, this could be helpful for people who need to watch their data and storage

**Comment by jackBonadies** [comment]
Hello, thank you for the suggestion.  Just to elaborate, do you mean on the download dialog page to have the total size for the folder displayed?

**Comment by jackBonadies** [comment]
This is fixed with https://github.com/jackBonadies/SeekerAndroid/commit/ca853182e4de2df525e558988533e1b91594f7bb
